### PR TITLE
UI: toggle-buttons

### PR DESCRIPTION
**Pull request by elysiumplain**

### CODE REVIEW

**Comment by elysiumplain** [comment]
Exit button Component swapped out temporarily for hardcoded button until I get to review impact of removing absolute positioning for the button style...Once this is complete, we can push a "leftside" layout template.

**Comment by serprex** [comment]
Removed ExitBtn from master

**Comment by serprex** [comment]
What's the problem with `display:grid`? It pairs with flexbox. I'm primarily looking to move away from littering `position:absolute` everywhere. Making the UI more responsive is ill fated without figuring out how to make `Match.jsx` responsive

**Comment by elysiumplain** [comment]
> Removed ExitBtn from master

Sorry for delay;

Pulling the exit button out was just because this is a progressive redesign (migrate UI chunks to Components is reasonable now with the change away from absolute and toward responsive layout).

You already have the top-end of this initiative with your "panes" wrapper, and likewise we seem to align with the grid/flex changes across Views over the last week.

**Comment by elysiumplain** [comment]
updated title for current UI change.

We can figure out the design/style as we go...but the idea of having a toggle-style component has merit. I'll reach out to Spex and get his input 

This adds intuition for what parts of UI are toggle-able, and the current state (particularly while new players may be trying to figure out the design-flow).

Notably, the "toggle" helps us resolve text-overflow with quite a few buttons.

**Comment by serprex** [comment]
Brought in most of this change with https://github.com/serprex/openEtG/commit/020752138db7d310b02a66729d2f4ffa4529c3aa except reusing selected instead of adding toggle-btn

**Pull request closed without merging**
